services:
  flask_api:
    build: ./python-api
    constainer_name: python_app
    ports: 
      - "5000:5000"
    volumes:
      - ./python-api:/app
    command: python app.py

  mysql_db:
    image: "mysql:8.0"
    environment:
      - MYSQL_USER=root
      - MYSQL_HOST=mysql_db
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=flask_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge
